#cloud-config

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: "https://discovery.etcd.io/2e790b5cd7c288e51eb6ae00b20a0f71"
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: "https://$private_ipv4:2379,https://$private_ipv4:4001"
    initial-advertise-peer-urls: "https://$private_ipv4:2380"
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: "https://0.0.0.0:2379,https://0.0.0.0:4001"
    # listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
    listen-peer-urls: "https://$private_ipv4:2380"

  fleet:
    etcd_servers: "https://$private_ipv4:4001"
    etcd_cafile: "/home/core/ca.pem"
    etcd_certfile: "/home/core/coreos.pem"
    etcd_keyfile: "/home/core/coreos-key.pem"
    public-ip: "$private_ipv4"
    metadata: "ephemeral=false"

  flannel:
    interface: "eth1"
    etcd_endpoints: "https://$private_ipv4:4001"
    etcd_cafile: "/home/core/ca.pem"
    etcd_certfile: "/home/core/coreos.pem"
    etcd_keyfile: "/home/core/coreos-key.pem"

  locksmith:
    endpoint: "https://$private_ipv4:4001"
    etcd_cafile: "/home/core/ca.pem"
    etcd_certfile: "/home/core/coreos.pem"
    etcd_keyfile: "/home/core/coreos-key.pem"

  update:
    reboot-strategy: off
    group: stable

  units:
    - name: "etcd2.service"
      command: "start"
      drop-ins:
        - name: "30-certificates.conf"
          content: |
            [Service]
            # client environment variables
            Environment=ETCD_CA_FILE=/home/core/ca.pem
            Environment=ETCD_CERT_FILE=/home/core/coreos.pem
            Environment=ETCD_KEY_FILE=/home/core/coreos-key.pem
            # peer environment variables
            Environment=ETCD_PEER_CA_FILE=/home/core/ca.pem
            Environment=ETCD_PEER_CERT_FILE=/home/core/coreos.pem
            Environment=ETCD_PEER_KEY_FILE=/home/core/coreos-key.pem
    - name: "fleet.service"
      command: "start"
    - name: "flanneld.service"
      command: start
    - name: "locksmith.service"
      command: start
    - name: iptables-restore.service
      enable: true
      command: start

write_files:
  - path: "/home/core/.bashrc"
    permissions: "0700"
    owner: "core:core"
    content: |
      set -o vi
      alias ll="ls -lah"
      alias ..="cd .."
      alias ...="cd ../.."
      export ETCDCTL_ENDPOINT=https://$private_ipv4:4001
      export ETCDCTL_CA_FILE=/home/core/ca.pem
      export ETCDCTL_CERT_FILE=/home/core/coreos.pem
      export ETCDCTL_KEY_FILE=/home/core/coreos-key.pem
  - path: "/home/core/private-ip.txt"
    permissions: "0640"
    owner: "core:core"
    content: |
      $private_ipv4
